/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.IoArgoprojWorkflowV1alpha1ArtifactResultNodeStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ArtifactGCStatus describes the result of the deletion
 */
@ApiModel(description = "ArtifactGCStatus describes the result of the deletion")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class IoArgoprojWorkflowV1alpha1ArtifactGCStatus {
  public static final String SERIALIZED_NAME_ARTIFACT_RESULTS_BY_NODE = "artifactResultsByNode";
  @SerializedName(SERIALIZED_NAME_ARTIFACT_RESULTS_BY_NODE)
  private Map<String, IoArgoprojWorkflowV1alpha1ArtifactResultNodeStatus> artifactResultsByNode = null;


  public IoArgoprojWorkflowV1alpha1ArtifactGCStatus artifactResultsByNode(Map<String, IoArgoprojWorkflowV1alpha1ArtifactResultNodeStatus> artifactResultsByNode) {
    
    this.artifactResultsByNode = artifactResultsByNode;
    return this;
  }

  public IoArgoprojWorkflowV1alpha1ArtifactGCStatus putArtifactResultsByNodeItem(String key, IoArgoprojWorkflowV1alpha1ArtifactResultNodeStatus artifactResultsByNodeItem) {
    if (this.artifactResultsByNode == null) {
      this.artifactResultsByNode = new HashMap<>();
    }
    this.artifactResultsByNode.put(key, artifactResultsByNodeItem);
    return this;
  }

   /**
   * ArtifactResultsByNode maps Node name to result
   * @return artifactResultsByNode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ArtifactResultsByNode maps Node name to result")

  public Map<String, IoArgoprojWorkflowV1alpha1ArtifactResultNodeStatus> getArtifactResultsByNode() {
    return artifactResultsByNode;
  }


  public void setArtifactResultsByNode(Map<String, IoArgoprojWorkflowV1alpha1ArtifactResultNodeStatus> artifactResultsByNode) {
    this.artifactResultsByNode = artifactResultsByNode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1ArtifactGCStatus ioArgoprojWorkflowV1alpha1ArtifactGCStatus = (IoArgoprojWorkflowV1alpha1ArtifactGCStatus) o;
    return Objects.equals(this.artifactResultsByNode, ioArgoprojWorkflowV1alpha1ArtifactGCStatus.artifactResultsByNode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(artifactResultsByNode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1ArtifactGCStatus {\n");
    sb.append("    artifactResultsByNode: ").append(toIndentedString(artifactResultsByNode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

