/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ArtifactResult describes the result of attempting to delete a given Artifact
 */
@ApiModel(description = "ArtifactResult describes the result of attempting to delete a given Artifact")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class IoArgoprojWorkflowV1alpha1ArtifactResult {
  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private String error;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SUCCESS = "success";
  @SerializedName(SERIALIZED_NAME_SUCCESS)
  private Boolean success;


  public IoArgoprojWorkflowV1alpha1ArtifactResult error(String error) {
    
    this.error = error;
    return this;
  }

   /**
   * Error is an optional error message which should be set if Success&#x3D;&#x3D;false
   * @return error
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Error is an optional error message which should be set if Success==false")

  public String getError() {
    return error;
  }


  public void setError(String error) {
    this.error = error;
  }


  public IoArgoprojWorkflowV1alpha1ArtifactResult name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name is the name of the Artifact
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Name is the name of the Artifact")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public IoArgoprojWorkflowV1alpha1ArtifactResult success(Boolean success) {
    
    this.success = success;
    return this;
  }

   /**
   * Success describes whether the deletion succeeded
   * @return success
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Success describes whether the deletion succeeded")

  public Boolean getSuccess() {
    return success;
  }


  public void setSuccess(Boolean success) {
    this.success = success;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1ArtifactResult ioArgoprojWorkflowV1alpha1ArtifactResult = (IoArgoprojWorkflowV1alpha1ArtifactResult) o;
    return Objects.equals(this.error, ioArgoprojWorkflowV1alpha1ArtifactResult.error) &&
        Objects.equals(this.name, ioArgoprojWorkflowV1alpha1ArtifactResult.name) &&
        Objects.equals(this.success, ioArgoprojWorkflowV1alpha1ArtifactResult.success);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, name, success);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1ArtifactResult {\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

