/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ClientCertAuth holds necessary information for client authentication via certificates
 */
@ApiModel(description = "ClientCertAuth holds necessary information for client authentication via certificates")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class IoArgoprojWorkflowV1alpha1ClientCertAuth {
  public static final String SERIALIZED_NAME_CLIENT_CERT_SECRET = "clientCertSecret";
  @SerializedName(SERIALIZED_NAME_CLIENT_CERT_SECRET)
  private io.kubernetes.client.openapi.models.V1SecretKeySelector clientCertSecret;

  public static final String SERIALIZED_NAME_CLIENT_KEY_SECRET = "clientKeySecret";
  @SerializedName(SERIALIZED_NAME_CLIENT_KEY_SECRET)
  private io.kubernetes.client.openapi.models.V1SecretKeySelector clientKeySecret;


  public IoArgoprojWorkflowV1alpha1ClientCertAuth clientCertSecret(io.kubernetes.client.openapi.models.V1SecretKeySelector clientCertSecret) {
    
    this.clientCertSecret = clientCertSecret;
    return this;
  }

   /**
   * Get clientCertSecret
   * @return clientCertSecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public io.kubernetes.client.openapi.models.V1SecretKeySelector getClientCertSecret() {
    return clientCertSecret;
  }


  public void setClientCertSecret(io.kubernetes.client.openapi.models.V1SecretKeySelector clientCertSecret) {
    this.clientCertSecret = clientCertSecret;
  }


  public IoArgoprojWorkflowV1alpha1ClientCertAuth clientKeySecret(io.kubernetes.client.openapi.models.V1SecretKeySelector clientKeySecret) {
    
    this.clientKeySecret = clientKeySecret;
    return this;
  }

   /**
   * Get clientKeySecret
   * @return clientKeySecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public io.kubernetes.client.openapi.models.V1SecretKeySelector getClientKeySecret() {
    return clientKeySecret;
  }


  public void setClientKeySecret(io.kubernetes.client.openapi.models.V1SecretKeySelector clientKeySecret) {
    this.clientKeySecret = clientKeySecret;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojWorkflowV1alpha1ClientCertAuth ioArgoprojWorkflowV1alpha1ClientCertAuth = (IoArgoprojWorkflowV1alpha1ClientCertAuth) o;
    return Objects.equals(this.clientCertSecret, ioArgoprojWorkflowV1alpha1ClientCertAuth.clientCertSecret) &&
        Objects.equals(this.clientKeySecret, ioArgoprojWorkflowV1alpha1ClientCertAuth.clientKeySecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientCertSecret, clientKeySecret);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojWorkflowV1alpha1ClientCertAuth {\n");
    sb.append("    clientCertSecret: ").append(toIndentedString(clientCertSecret)).append("\n");
    sb.append("    clientKeySecret: ").append(toIndentedString(clientKeySecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

